name: habit_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.14
  flutter_hooks: ^0.20.5
  intl: ^0.19.0                     # Zaktualizowana wersja intl
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  hooks_riverpod: ^2.1.3
  google_sign_in: ^6.2.2
  email_validator: ^3.0.0
  shared_preferences: ^2.3.3
  flutter_facebook_auth: ^7.1.1
  cloud_firestore: ^5.5.0
  web: ^1.0.0                         # Dodanie wersji web
  rename: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Klasik
      fonts:
        - asset: fonts/Klasik-Regular.ttf
    - family: Manrope
      fonts:
        - asset: fonts/Manrope-Bold.ttf
        - asset: fonts/Manrope-ExtraBold.ttf
        - asset: fonts/Manrope-ExtraLight.ttf
        - asset: fonts/Manrope-Light.ttf
        - asset: fonts/Manrope-Medium.ttf
        - asset: fonts/Manrope-Regular.ttf
        - asset: fonts/Manrope-SemiBold.ttf
